import IntroFlutter from "../code/01_Intro";
import { FlutterSdk } from "../code/02_flutterSdk";
import Widgets from "../code/03_Widgets";

const flutterContent = {
  about: {
    name: "Flutter dfdf",
    description: "Learn about photography.",
    link: "",
    img: "design.jpg",
  },
  route: [
    {
      heading: "Introduction to Flutter",
      topic: "Getting Started",
      page: <IntroFlutter />,
    },
    { topic: "Setup Guide", page: <FlutterSdk /> },
    {
      heading: "Understanding Widgets",
      topic: "Widget Basics",
      page: <Widgets />,
    },
    { topic: "State Management", page: <Widgets /> },
    {
      heading: "Dart Basics",
      topic: "Programming Language",
      page: <IntroFlutter />,
    },
    { topic: "Folder Organization", page: <IntroFlutter /> },
    {
      heading: "Creating Your First App",
      topic: "Beginner Guide",
      page: <IntroFlutter />,
    },
    {
      heading: "Hot Reload and Hot Restart",
      topic: "Development Tools",
      page: <IntroFlutter />,
    },
    { topic: "UI Components", page: <Widgets /> },
    {
      heading: "Exploring Cupertino Widgets",
      topic: "iOS Design",
      page: <Widgets />,
    },
    {
      heading: "Flutter Layout Basics",
      topic: "Layout Guide",
      page: <IntroFlutter />,
    },
    { topic: "Layout Elements", page: <Widgets /> },
    {
      heading: "Columns and Stacks in Flutter",
      topic: "Advanced Layout",
      page: <Widgets />,
    },
    { heading: "Adding Interactivity", topic: "User Input", page: <Widgets /> },
    { topic: "Form Fields", page: <Widgets /> },
    {
      heading: "Navigation in Flutter",
      topic: "Routing",
      page: <IntroFlutter />,
    },
    {
      heading: "Named Routes",
      topic: "Advanced Routing",
      page: <IntroFlutter />,
    },
    { topic: "Navigation", page: <IntroFlutter /> },
    {
      heading: "State Management Basics",
      topic: "Provider Introduction",
      page: <IntroFlutter />,
    },
    { topic: "State Management", page: <IntroFlutter /> },
    {
      heading: "Introduction to Riverpod",
      topic: "State Management",
      page: <IntroFlutter />,
    },
    {
      heading: "Flutter Animations",
      topic: "Adding Motion",
      page: <Widgets />,
    },
    { topic: "Advanced Motion", page: <Widgets /> },
    {
      heading: "Networking in Flutter",
      topic: "HTTP Requests",
      page: <IntroFlutter />,
    },
    { topic: "JSON Handling", page: <IntroFlutter /> },
    {
      heading: "Parsing JSON Data",
      topic: "API Integration",
      page: <IntroFlutter />,
    },
    {
      heading: "Using Firebase with Flutter",
      topic: "Cloud Integration",
      page: <IntroFlutter />,
    },
    { topic: "Login Systems", page: <IntroFlutter /> },
    {
      heading: "Real-Time Database in Flutter",
      topic: "Firebase Database",
      page: <IntroFlutter />,
    },
    {
      heading: "Working with Firestore",
      topic: "Cloud Firestore",
      page: <IntroFlutter />,
    },
    { topic: "Firebase Messaging", page: <IntroFlutter /> },
    {
      heading: "Introduction to Bloc",
      topic: "State Management",
      page: <IntroFlutter />,
    },
    { topic: "State Management", page: <IntroFlutter /> },
    {
      heading: "Building Responsive Apps",
      topic: "Adaptive Design",
      page: <IntroFlutter />,
    },
    {
      heading: "Flutter and Accessibility",
      topic: "Inclusive Design",
      page: <IntroFlutter />,
    },
    { topic: "External Libraries", page: <IntroFlutter /> },
    {
      heading: "Creating Custom Widgets",
      topic: "Reusable Components",
      page: <Widgets />,
    },
    {
      heading: "Advanced Dart Techniques",
      topic: "Efficient Coding",
      page: <IntroFlutter />,
    },
    { topic: "Error Handling", page: <IntroFlutter /> },
    {
      heading: "Introduction to Testing",
      topic: "Unit Tests",
      page: <IntroFlutter />,
    },
    {
      heading: "Widget Testing",
      topic: "Test UI Components",
      page: <IntroFlutter />,
    },
    { topic: "Comprehensive Testing", page: <IntroFlutter /> },
    {
      heading: "Localization in Flutter",
      topic: "Multi-Language Apps",
      page: <IntroFlutter />,
    },
    {
      heading: "Flutter and AR",
      topic: "Augmented Reality",
      page: <IntroFlutter />,
    },
    { topic: "Geolocation", page: <IntroFlutter /> },
    {
      heading: "Accessing Device Features",
      topic: "Platform Channels",
      page: <IntroFlutter />,
    },
    { topic: "Flutter Web", page: <IntroFlutter /> },
    {
      heading: "Deploying Apps",
      topic: "Publishing Guide",
      page: <IntroFlutter />,
    },
    {
      heading: "Optimizing Flutter Apps",
      topic: "Performance",
      page: <IntroFlutter />,
    },
    { topic: "Cross-Platform", page: <IntroFlutter /> },
    {
      heading: "Introduction to Null Safety",
      topic: "Dart Features",
      page: <IntroFlutter />,
    },
    {
      heading: "Error Boundaries in Flutter",
      topic: "Crash Safety",
      page: <IntroFlutter />,
    },
    { topic: "User Input", page: <Widgets /> },
    { topic: "User Input", page: <Widgets /> },
    {
      heading: "In-App Purchases",
      topic: "Monetization",
      page: <IntroFlutter />,
    },
    { topic: "Ads in Apps", page: <IntroFlutter /> },
    {
      heading: "Flutter Inspector",
      topic: "Debugging UI",
      page: <IntroFlutter />,
    },
    { topic: "User Input", page: <IntroFlutter /> },
    {
      heading: "Exploring Flutter DevTools",
      topic: "Advanced Debugging",
      page: <IntroFlutter />,
    },
    { topic: "Styling", page: <IntroFlutter /> },
    {
      heading: "Dark Mode Implementation",
      topic: "Theming",
      page: <IntroFlutter />,
    },
    {
      heading: "Shared Preferences",
      topic: "Local Storage",
      page: <IntroFlutter />,
    },
    { topic: "Database", page: <IntroFlutter /> },
    {
      heading: "Secure Storage",
      topic: "Sensitive Data",
      page: <IntroFlutter />,
    },
    { topic: "Real-Time Features", page: <IntroFlutter /> },
    {
      heading: "Implementing Social Logins",
      topic: "OAuth",
      page: <IntroFlutter />,
    },
    {
      heading: "Async Programming in Dart",
      topic: "Futures and Streams",
      page: <IntroFlutter />,
    },
    { topic: "Reactive Programming", page: <IntroFlutter /> },
    { heading: "Drag and Drop", topic: "Interactive UI", page: <Widgets /> },
    { topic: "State Management", page: <IntroFlutter /> },
    {
      heading: "Working with Animations",
      topic: "Motion Effects",
      page: <Widgets />,
    },
    { topic: "Custom Scroll", page: <Widgets /> },
    {
      heading: "Introduction to Flutter WebSockets",
      topic: "Real-Time Data",
      page: <IntroFlutter />,
    },
    { topic: "API Querying", page: <IntroFlutter /> },
    {
      heading: "Introduction to Flutter Hooks",
      topic: "Advanced State Management",
      page: <IntroFlutter />,
    },
    { topic: "Automated Deployment", page: <IntroFlutter /> },
    {
      heading: "Flutter in Enterprise Apps",
      topic: "Large Scale Projects",
      page: <IntroFlutter />,
    },
    {
      heading: "Custom Painter in Flutter",
      topic: "Graphics and Design",
      page: <Widgets />,
    },
    { topic: "Smart Devices", page: <IntroFlutter /> },
    {
      heading: "Handling Permissions",
      topic: "Platform Features",
      page: <IntroFlutter />,
    },
    {
      heading: "Building Offline Apps",
      topic: "Data Caching",
      page: <IntroFlutter />,
    },
    { topic: "Native Integration", page: <IntroFlutter /> },
    { heading: "Dynamic Links", topic: "Deep Linking", page: <IntroFlutter /> },
    { topic: "Machine Learning", page: <IntroFlutter /> },
    {
      heading: "Exploring Custom Fonts",
      topic: "Typography",
      page: <IntroFlutter />,
    },
    { topic: "Library Selection", page: <IntroFlutter /> },
    {
      heading: "Handling Errors Gracefully",
      topic: "Error UI",
      page: <IntroFlutter />,
    },
    { topic: "Quick Development", page: <IntroFlutter /> },
    {
      heading: "Flutter for Gaming",
      topic: "Game Development",
      page: <IntroFlutter />,
    },
    { topic: "Flutter and Devices", page: <IntroFlutter /> },
    {
      heading: "Voice Assistants",
      topic: "Speech Recognition",
      page: <IntroFlutter />,
    },
    { topic: "Data Visualization", page: <Widgets /> },
    {
      heading: "Working with Grids",
      topic: "Advanced Layouts",
      page: <Widgets />,
    },
    {
      heading: "Flutter SEO",
      topic: "Web Optimization",
      page: <IntroFlutter />,
    },
    { topic: "Version Upgrades", page: <IntroFlutter /> },
  ],
};

export default flutterContent;
