fileList = [
    "Css Reference",
    "Selectors",
    "Units",
    "Font",
    "Cursor",
    "Background",
    "Box Sizing",
    "Opacity",
    "Text",
    "List Styling",
    "Margin",
    "Padding",
    "Border",
    "Display",
    "Table",
    "Parent And Child",
    "Border Radius",
    "Colors",
    "Box Shadow",
    "Chess",
    "Layout",
    "Visibility",
    "Z Index",
    "Outline",
    "Min And Max H",
    "Min And Max W",
    "Overflow",
    "Column",
    "Transition",
    "Float And Clear",
    "Vertical Center",
    "Basic Code Setup",
    "Flex Inlineflex",
    "Flex Direction",
    "Flex Wrap",
    "Flex Flow",
    "F Gap",
    "Justify Content",
    "Align Items",
    "Align Content",
    "Flex Order",
    "Flex Grow",
    "Flex Shrink",
    "Flex Basis",
    "Flex",
    "Align Self",
    "Basic Code Setup G",
    "Grid Inlinegrid",
    "Grid Template Columns",
    "Grid Template Rows",
    "Grid Templates",
    "Grid Gap",
    "Justify Items",
    "Align Items",
    "Place Items",
    "Justify Content",
    "Align Content",
    "Place Content",
    "Grid Auto Flow",
    "Grid Column",
    "Grid Row",
    "Justify Self",
    "Align Self",
    "Place Self",
    "Grid Template Area",
    "Stylishpreferences",
]
